### ISSUE TITLE
Did you manage to solve this?

### ISSUE THREAD

**Issue by stam** [PheelaV/MultipleVueRootAppsMultipleEntryFilesSameStore#1]
Hey, did you manage to solve this?

I encountered the same thing, found a lot of people with similar issues online, but no proper fix.

**Comment by PheelaV** [comment]
Hiya, unfortunately not, it has been shelved. The last route I was probing was defining vue as an external dependency. I do not remember what problems I've hit after that. I think it had something to do with our use-case of the vue CLI. Did not give webpack a try yet. I presume you have seen my [SO post](https://stackoverflow.com/questions/69775876/multiple-vue-apps-multiple-entry-files-same-vuex-vue3compostitionapi-store-lo). There is some new activity which goes deeper into the problematic that is likely the root cause of this.

**Comment by stam** [comment]
Thanks for the reply, shame to hear that you also didn't find a fix. Our approach currently is to have a temporary fix in place until we move to a single Vue bundle.

I find it weird that Vue gets a lot of praise for better allowing micro frontends, but if you dig deep down everything falls apart

EDIT: If someone else encounters this issue: 
My temporary fix was to just not use a store shared through the window, but to have each separate bundle have its own store, and make sure the data is shared "outside" vuex, and loaded in each separate instance of the vuex store
